# konfigurasi oauth2 di spring 1.5.*
security:
    oauth2:
        resource:
            filter-order: 3

spring:

    #konfigurasi jackson
    jackson:
        serialization:
            indent-output: true

    # spring datasource jpa
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/auth_server?autoReconnect=true
        username: root
        password:
        poolName: SpringBootHikariCP
        maximumPoolSize: 5
        minimumIdle: 3
        maxLifetime: 2000000
        connectionTimeout: 30000
        idleTimeout: 30000

    # spring hibernate
    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8081
